### ISSUE TITLE
Regarding the padding in segments

### ISSUE THREAD

**Issue by satyandraguthula** [coastalcph/hierarchical-transformers#6]
Hi, In the code I can see that you are merging some sentences till the max segment length is reached. Why is this being done instead of not using the segments/sentences as is? I need the representations for each segment as well, so for me I don't think merging the segments is useful. I can see that in some cases the standard BERT without having the hierarchy in place is performing better (provided I changed the HAT code to not merge segments). I wanted to know if you also found similar issues due to padded zeros in segments which leads to intermittent padded zeros in the document.

**Comment by iliaschalkidis** [comment]
Hi @satyandraguthula,

We briefly discuss this point in the paper. I think it's an open debate and there are pros and cons. The main reason we promote merging is avoid over-padding the fixed-length model segments - in case of short sentences- with fake pad tokens and as a result over-truncate the document.

In many cases though, someone may want to have a one-to-one correspondence between actual sentences or paragraphs and model segments, eg, for hierarchical sentence classification tasks, or just because they want to experiment with distinct segments and explore this direction. That's why I recently updated the tokenizer to make this possible out-of-the-box:

https://github.com/coastalcph/hierarchical-transformers/blob/34a631391347f115d96e3e676ec9c58b7b33325f/models/hat/tokenization_hat.py#L108
